# Generated by Django 3.1.2 on 2020-12-31 00:38

from django.db import migrations, models
import django.db.models.deletion
import djangocms_text_ckeditor.fields
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='name')),
            ],
            options={
                'verbose_name': 'gallery',
                'verbose_name_plural': 'galleries',
            },
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='slider_slider', serialize=False, to='cms.cmsplugin')),
                ('title', models.CharField(blank=True, max_length=128, null=True, verbose_name='title')),
                ('description', djangocms_text_ckeditor.fields.HTMLField(blank=True, null=True, verbose_name='description')),
                ('gallery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='slider.gallery', verbose_name='gallery')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=128, null=True, verbose_name='title')),
                ('file', sorl.thumbnail.fields.ImageField(upload_to='images', verbose_name='file')),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slider.gallery')),
            ],
            options={
                'verbose_name': 'photo',
                'verbose_name_plural': 'photo',
            },
        ),
    ]
