# Generated by Django 3.1.2 on 2020-10-25 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'Задача', 'verbose_name_plural': 'Задачи'},
        ),
        migrations.AddField(
            model_name='task',
            name='image',
            field=models.ImageField(blank=True, help_text='150x150px', upload_to='image/blog/%Y/%m/%d', verbose_name='Ссылка картинки'),
        ),
    ]
