# Generated by Django 3.1.2 on 2020-11-28 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20201118_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='file',
            field=models.FileField(blank=True, upload_to='Files/%Y/%m/%d', verbose_name='Ссылка файла'),
        ),
        migrations.AlterField(
            model_name='task',
            name='image',
            field=models.ImageField(blank=True, upload_to='image/', verbose_name='Ссылка картинки'),
        ),
        migrations.AlterField(
            model_name='taskimage',
            name='image',
            field=models.ImageField(blank=True, upload_to='image/blog', verbose_name='Ссылка картинки'),
        ),
    ]
